export interface ConditionFaq {
  question: string;
  answer: string;
}

export interface ConditionPageContent {
  slug: string;
  name: string;
  title: string;
  metaDescription: string;
  intro: string;
  symptoms: string[];
  causes: string[];
  diagnosis: string[];
  treatment: string[];
  benefits: string[];
  recoveryTimeline: string;
  relatedServices: string[];
  faqs: ConditionFaq[];
}

/**
 * Public condition content is intentionally written as general education.
 * It must be reviewed by an appropriately licensed clinician before launch.
 * Never use these pages to diagnose a visitor or promise an outcome.
 */
export const conditionPages: ConditionPageContent[] = [
  {
    slug: "fracture-rehabilitation",
    name: "Fracture Rehabilitation",
    title: "Fracture Rehabilitation in Lipa City",
    metaDescription: "Learn how physical therapy may support mobility, strength, and safe activity after a fracture or fracture-related surgery.",
    intro: "Rehabilitation after a fracture is planned around bone healing, medical restrictions, movement goals, and the activities you need to resume.",
    symptoms: ["Pain, swelling, or tenderness around the injured area", "Reduced joint movement or difficulty using the limb", "Weakness, stiffness, or changes in walking after immobilization"],
    causes: ["Falls, sports injuries, vehicle or workplace accidents", "Repetitive stress or overuse injuries", "Reduced strength or balance that increases fall risk"],
    diagnosis: ["A physician or qualified medical provider examines the injury and may use X-rays or other imaging", "A rehabilitation clinician reviews movement, strength, balance, swelling, function, and any medical restrictions after clearance", "The rehabilitation plan is coordinated with the treating physician or surgeon when needed"],
    treatment: ["Gradual mobility and strengthening within the approved healing limits", "Gait, balance, transfer, or upper-limb function training", "Education for safe loading, home exercises, and return to daily activities", "Scar, swelling, or stiffness management when clinically appropriate"],
    benefits: ["Improved movement and confidence with daily activities", "Progressive restoration of strength and balance", "A clearer, safer path back to work, school, exercise, or sport"],
    recoveryTimeline: "Recovery depends on the bone, fracture pattern, treatment, age, general health, and medical restrictions. Progress is usually staged and should follow the treating clinician’s clearance rather than a fixed deadline.",
    relatedServices: ["Physical Therapy Evaluation & Rehabilitation", "Sports Injury Rehabilitation"],
    faqs: [{ question: "When can therapy begin after a fracture?", answer: "The timing depends on the fracture and the treating medical provider’s instructions. Contact the clinic with your clearance or referral so the plan can be tailored safely." }],
  },
  {
    slug: "hip-replacement-rehabilitation",
    name: "Total and Partial Hip Replacement Rehabilitation",
    title: "Hip Replacement Rehabilitation in Lipa City",
    metaDescription: "Learn what rehabilitation may involve after total or partial hip replacement, including mobility, strength, and daily-activity goals.",
    intro: "Rehabilitation after total or partial hip replacement supports safe mobility and confidence while respecting surgical precautions and the pace of healing.",
    symptoms: ["Post-operative pain, swelling, stiffness, or fatigue", "Difficulty walking, transferring, or using stairs", "Weakness around the hip and changes in balance or endurance"],
    causes: ["Hip joint damage from arthritis or injury", "Fracture or other conditions requiring partial replacement", "Surgical recovery needs after joint replacement"],
    diagnosis: ["The surgeon or medical team provides the surgical diagnosis, precautions, and weight-bearing instructions", "A therapist evaluates walking, transfers, range of motion, strength, balance, and daily tasks", "Progress is adjusted based on symptoms, healing, precautions, and medical follow-up"],
    treatment: ["Bed mobility, transfers, walking, and stair practice", "Progressive hip and lower-limb strengthening", "Balance, endurance, and home-safety training", "Education about precautions, equipment, pacing, and home exercises"],
    benefits: ["Safer movement at home and in the community", "Improved confidence with walking and daily tasks", "A structured progression toward appropriate activity"],
    recoveryTimeline: "Recovery varies between total and partial replacement and is affected by surgical approach, health, strength, home support, and complications. Your surgeon and rehabilitation clinician should set the activity milestones.",
    relatedServices: ["Physical Therapy Evaluation & Rehabilitation", "Occupational Therapy & Daily-Activity Retraining"],
    faqs: [{ question: "Is rehabilitation different after total and partial hip replacement?", answer: "Some goals overlap, but precautions and progression can differ. The rehabilitation plan should follow the specific surgery and instructions from your medical team." }],
  },
  {
    slug: "frozen-shoulder",
    name: "Frozen Shoulder",
    title: "Frozen Shoulder Rehabilitation in Lipa City",
    metaDescription: "Understand frozen shoulder symptoms, evaluation, treatment options, and realistic recovery considerations with FlexTend rehabilitation support.",
    intro: "Frozen shoulder can make reaching, dressing, sleeping, and everyday arm use difficult. Rehabilitation focuses on an individualized balance of mobility, comfort, and function.",
    symptoms: ["Gradually increasing shoulder pain or stiffness", "Difficulty reaching overhead, behind the back, or across the body", "Sleep and dressing difficulties because of limited movement"],
    causes: ["The condition may occur without a clear trigger", "Reduced shoulder movement after injury, surgery, or illness may contribute", "Some medical conditions may be associated with a higher risk and should be discussed with a provider"],
    diagnosis: ["A medical provider reviews the history and examines active and passive shoulder movement", "Imaging may be used to rule out other causes when indicated", "A therapist assesses functional movement, irritability, strength, and daily goals"],
    treatment: ["Education about pacing and comfortable movement", "Individualized mobility exercises and activity modification", "Progressive strengthening when movement and irritability allow", "Home-program coaching and review of symptom response"],
    benefits: ["Better ability to perform dressing, reaching, and household tasks", "Improved shoulder mobility and confidence", "A plan that avoids forcing painful movement beyond the person’s tolerance"],
    recoveryTimeline: "Frozen shoulder often changes over time, but the pattern and duration vary widely. Improvement may be gradual, and the appropriate pace depends on irritability, health, function, and response to care.",
    relatedServices: ["Physical Therapy Evaluation & Rehabilitation", "Dry Needling & Myofascial Therapy"],
    faqs: [{ question: "Should I force my shoulder to move?", answer: "Do not assume that more force is better. A clinician can help identify a safe movement range and a plan that matches your symptoms and medical history." }],
  },
  {
    slug: "arthritis-rehabilitation",
    name: "Arthritis Rehabilitation",
    title: "Arthritis Rehabilitation and Mobility Support",
    metaDescription: "Explore rehabilitation strategies for arthritis-related pain, stiffness, strength, mobility, and daily activity goals in Lipa City.",
    intro: "Rehabilitation for arthritis is designed around the joints affected, symptom patterns, activity goals, and the person’s confidence with movement.",
    symptoms: ["Joint pain or stiffness", "Swelling or reduced range of motion", "Difficulty with walking, stairs, gripping, or prolonged activity"],
    causes: ["Different types of arthritis have different causes", "Joint injury, age-related changes, inflammation, or other health conditions may contribute", "A medical assessment is important when symptoms are new, severe, or changing"],
    diagnosis: ["A physician or qualified provider determines the medical diagnosis when needed", "A therapist evaluates movement, strength, balance, task tolerance, and goals", "The team considers symptoms and function rather than relying on pain alone"],
    treatment: ["Strengthening and mobility exercises matched to tolerance", "Pacing, joint-protection, and activity-modification education", "Walking, balance, or task training when lower-limb function is affected", "Home strategies to support consistent, manageable activity"],
    benefits: ["More confidence with daily movement", "Improved strength, mobility, and activity tolerance", "Practical strategies for managing flares and maintaining participation"],
    recoveryTimeline: "Arthritis is often managed over time rather than through one fixed recovery period. Progress depends on the type of arthritis, other health factors, consistency, and response to the plan.",
    relatedServices: ["Physical Therapy Evaluation & Rehabilitation", "Occupational Therapy & Daily-Activity Retraining"],
    faqs: [{ question: "Can exercise help when a joint is painful?", answer: "Many people benefit from appropriately dosed movement, but the right exercises depend on the joint, diagnosis, symptoms, and health history. An evaluation can help identify a safe starting point." }],
  },
  {
    slug: "hip-knee-back-pain",
    name: "Hip, Knee and Back Pain",
    title: "Hip, Knee and Back Pain Rehabilitation",
    metaDescription: "Learn how a rehabilitation evaluation may help with hip, knee, or back pain affecting movement and daily activities.",
    intro: "Hip, knee, and back pain can affect walking, work, sleep, exercise, and confidence. A rehabilitation plan starts by understanding the person and the movement problem rather than treating a label alone.",
    symptoms: ["Pain with walking, sitting, lifting, stairs, or exercise", "Stiffness, weakness, or reduced range of motion", "Changes in balance, gait, posture, or activity tolerance"],
    causes: ["Muscle, tendon, joint, nerve, or movement-related factors", "Injury, surgery, repeated loading, or reduced activity", "Some symptoms may require medical evaluation to rule out non-musculoskeletal causes"],
    diagnosis: ["A clinician takes a history and screens for signs that need medical referral", "Movement, strength, mobility, balance, and task tolerance are assessed", "The working plan is updated as symptoms and function change"],
    treatment: ["Education and activity modification", "Progressive mobility, strengthening, and motor-control exercises", "Gait, lifting, balance, or sport-specific retraining", "A home program that can be adjusted as tolerance improves"],
    benefits: ["Improved movement confidence and activity tolerance", "Better understanding of factors that affect symptoms", "A practical plan for returning to meaningful daily activities"],
    recoveryTimeline: "The timeline depends on the cause, severity, duration, health factors, and response to care. A clinician can help set short-term functional goals and review progress over time.",
    relatedServices: ["Physical Therapy Evaluation & Rehabilitation", "Sports Injury Rehabilitation", "Dry Needling & Myofascial Therapy"],
    faqs: [{ question: "When should pain be checked urgently?", answer: "Seek urgent care for severe or rapidly worsening symptoms, major trauma, new weakness or loss of sensation, loss of bladder or bowel control, chest pain, or other emergency symptoms." }],
  },
  {
    slug: "scoliosis",
    name: "Scoliosis",
    title: "Scoliosis Rehabilitation and Movement Support",
    metaDescription: "Learn how physical therapy may support strength, posture, movement confidence, and function for people living with scoliosis.",
    intro: "Scoliosis care depends on age, curve characteristics, symptoms, growth, previous treatment, and personal goals. Rehabilitation works alongside appropriate medical follow-up.",
    symptoms: ["Uneven shoulder or hip position", "Changes in posture or spinal alignment", "Back discomfort, fatigue, reduced endurance, or movement concerns"],
    causes: ["Some curves develop during growth without a single known cause", "Other curves may be associated with congenital, neuromuscular, degenerative, or other conditions", "A medical provider should assess new or changing spinal symptoms"],
    diagnosis: ["A medical provider assesses posture and spinal alignment and may request imaging", "A therapist evaluates movement, breathing or trunk control when relevant, strength, balance, and function", "The plan is coordinated with the treating provider, especially for growing children or complex cases"],
    treatment: ["Individualized trunk, hip, and shoulder strength work", "Posture, balance, breathing, and movement education when appropriate", "Activity and school or work strategies", "Family education and coordination with medical or orthotic care when needed"],
    benefits: ["Improved confidence with movement and activity", "Better strength, balance, and functional tolerance", "Practical strategies that support participation without promising curve correction"],
    recoveryTimeline: "Scoliosis management is individualized and may be ongoing. Goals and monitoring depend on growth, curve behavior, symptoms, medical treatment, and functional needs.",
    relatedServices: ["Physical Therapy Evaluation & Rehabilitation", "Pediatric Physical & Occupational Therapy"],
    faqs: [{ question: "Can therapy replace scoliosis monitoring?", answer: "No. Rehabilitation can support function and movement goals, but medical monitoring and any prescribed bracing or surgical care remain important when indicated." }],
  },
  {
    slug: "generalized-body-weakness",
    name: "Generalized Body Weakness",
    title: "Generalized Body Weakness Rehabilitation",
    metaDescription: "Explore rehabilitation support for generalized weakness, reduced endurance, balance changes, and difficulty with daily activities.",
    intro: "Generalized weakness is a symptom with many possible causes. Rehabilitation begins with safety screening and coordination with medical care when the cause is not known.",
    symptoms: ["Reduced strength in several areas of the body", "Fatigue or reduced endurance during everyday tasks", "Difficulty with transfers, walking, stairs, balance, or self-care"],
    causes: ["Deconditioning after illness, hospitalization, or prolonged inactivity", "Neurological, musculoskeletal, cardiopulmonary, nutritional, or medication-related factors", "New or rapidly worsening weakness requires medical assessment"],
    diagnosis: ["A medical provider investigates the cause when weakness is new, unexplained, or changing", "A therapist evaluates strength, endurance, balance, mobility, and daily tasks", "The rehabilitation plan is modified for fatigue, safety, and medical precautions"],
    treatment: ["Graded strengthening and endurance activities", "Transfer, walking, stair, and balance practice", "Energy-conservation and pacing education", "Home and caregiver strategies that support safe participation"],
    benefits: ["Safer mobility and transfers", "Improved tolerance for daily routines", "Better confidence with pacing and activity planning"],
    recoveryTimeline: "The timeline depends primarily on the underlying cause, medical stability, baseline function, and available support. Progress should be monitored rather than measured against a guaranteed schedule.",
    relatedServices: ["Physical Therapy Evaluation & Rehabilitation", "Occupational Therapy & Daily-Activity Retraining", "Neurological Rehabilitation"],
    faqs: [{ question: "Is generalized weakness always a therapy problem?", answer: "No. Weakness can have medical causes that need evaluation. Contact a medical provider promptly if weakness is new, sudden, one-sided, worsening, or accompanied by other concerning symptoms." }],
  },
  {
    slug: "myofascial-pain-syndrome",
    name: "Myofascial Pain Syndrome",
    title: "Myofascial Pain Syndrome Rehabilitation",
    metaDescription: "Learn about rehabilitation approaches for myofascial pain, muscle sensitivity, movement limitations, and activity goals.",
    intro: "Myofascial pain can involve sensitive muscle areas, stiffness, and activity-related symptoms. Care should combine assessment, movement, education, and realistic self-management strategies.",
    symptoms: ["Localized or regional muscle pain and sensitivity", "Stiffness or reduced movement", "Pain that changes with activity, posture, pressure, or sustained positions"],
    causes: ["Muscle overuse, sustained loading, injury, stress, or reduced movement may contribute", "Several factors can interact, and symptoms are not always explained by one tissue", "A clinician should screen for other causes when symptoms are new or atypical"],
    diagnosis: ["Diagnosis is based on history and a physical examination by a qualified provider", "A therapist evaluates movement, strength, load tolerance, and functional triggers", "The plan is reviewed if symptoms do not behave as expected"],
    treatment: ["Graded mobility and strengthening", "Education about pacing, posture, activity variation, and sleep or recovery habits", "Manual therapy or dry needling only when appropriate and consented to", "A home program focused on sustainable function rather than short-term pain chasing"],
    benefits: ["Improved movement confidence and task tolerance", "Better understanding of contributing activity patterns", "More sustainable strategies for managing recurring symptoms"],
    recoveryTimeline: "Symptoms may improve gradually and can fluctuate. Progress depends on the contributing factors, duration, sleep and stress, activity demands, and response to a consistent plan.",
    relatedServices: ["Dry Needling & Myofascial Therapy", "Physical Therapy Evaluation & Rehabilitation"],
    faqs: [{ question: "Is dry needling required for myofascial pain?", answer: "No. It is only one possible option and may not be appropriate for everyone. A clinician should discuss the evaluation findings, alternatives, risks, and expected goals with you." }],
  },
  {
    slug: "bells-palsy",
    name: "Bell's Palsy",
    title: "Bell's Palsy Rehabilitation Support",
    metaDescription: "Learn about rehabilitation considerations after Bell's palsy, including facial movement, function, safety, and medical follow-up.",
    intro: "Bell’s palsy involves sudden weakness of facial muscles and needs prompt medical assessment because other causes of facial weakness must be considered.",
    symptoms: ["Weakness or reduced movement on one side of the face", "Difficulty closing one eye, smiling, or controlling facial movement", "Changes in taste, sound sensitivity, or facial comfort may occur"],
    causes: ["Bell’s palsy is associated with inflammation affecting the facial nerve", "Facial weakness can also occur with stroke or other conditions, so sudden symptoms must be assessed urgently", "Your medical provider determines the diagnosis and treatment"],
    diagnosis: ["A medical provider assesses the pattern and timing of facial weakness and other neurological signs", "Additional tests may be used when the presentation is unusual or another cause is suspected", "A therapist evaluates facial movement, function, eye-safety routines, and communication concerns when referred"],
    treatment: ["Follow the medical plan and protect the eye if it does not close fully", "Gentle, individualized facial movement and function support when appropriate", "Education for communication, eating, and daily tasks", "Coordination with medical, ophthalmology, or speech-language providers when needed"],
    benefits: ["Safer management of eye and facial-function concerns", "Better confidence with communication and daily activities", "Coordinated rehabilitation that respects nerve recovery and medical guidance"],
    recoveryTimeline: "Recovery varies considerably. Do not use a fixed timeline to judge your condition; follow medical review, especially if symptoms worsen, new neurological signs appear, or eye protection is difficult.",
    relatedServices: ["Neurological Rehabilitation", "Occupational Therapy & Daily-Activity Retraining"],
    faqs: [{ question: "When is facial weakness an emergency?", answer: "Sudden facial weakness with arm or leg weakness, speech difficulty, confusion, severe headache, vision changes, or loss of balance may indicate an emergency. Seek emergency care immediately." }],
  },
  {
    slug: "stroke-rehabilitation",
    name: "Stroke",
    title: "Stroke Rehabilitation in Lipa City",
    metaDescription: "Explore physical and occupational therapy support after stroke, including mobility, balance, upper-limb function, and daily activities.",
    intro: "Stroke rehabilitation is coordinated around the person’s neurological changes, medical status, goals, home environment, and ability to participate safely.",
    symptoms: ["Changes in strength, coordination, sensation, balance, or walking", "Difficulty using an arm or hand or completing daily activities", "Changes in communication, swallowing, vision, attention, or fatigue may also occur"],
    causes: ["A stroke can result from interrupted blood flow or bleeding in the brain", "Risk factors and the type of stroke vary between people", "New stroke symptoms require emergency care rather than an outpatient therapy appointment"],
    diagnosis: ["The hospital or medical team diagnoses the stroke and identifies the affected systems", "Therapists assess mobility, balance, transfers, upper-limb use, daily activities, endurance, and safety", "Care may be coordinated with physicians, nurses, speech-language professionals, and caregivers"],
    treatment: ["Task-specific practice for transfers, walking, balance, reaching, and daily activities", "Strength, coordination, endurance, and positioning work as appropriate", "Occupational therapy for self-care, home tasks, and environmental strategies", "Caregiver education and a safe home program"],
    benefits: ["Safer mobility and daily participation", "Improved confidence with transfers, walking, or self-care", "A coordinated plan that adapts as recovery and goals change"],
    recoveryTimeline: "Stroke recovery varies with the type and location of stroke, medical complications, severity, timing, support, and participation. Progress may continue over different stages and should be reviewed regularly.",
    relatedServices: ["Neurological Rehabilitation", "Occupational Therapy & Daily-Activity Retraining"],
    faqs: [{ question: "Can therapy start after discharge from the hospital?", answer: "Many people continue rehabilitation after discharge, but the right setting and timing depend on medical stability, function, and the discharge plan. Bring your medical instructions to the evaluation." }],
  },
  {
    slug: "spinal-cord-injury",
    name: "Spinal Cord Injury",
    title: "Spinal Cord Injury Rehabilitation Support",
    metaDescription: "Learn how rehabilitation may support mobility, transfers, strength, self-care, and participation after spinal cord injury.",
    intro: "Spinal cord injury rehabilitation is highly individualized and must follow medical precautions, neurological level, completeness of injury, and the person’s goals.",
    symptoms: ["Changes in strength, sensation, movement, or trunk control", "Difficulty with transfers, walking, wheelchair skills, or self-care", "Changes in endurance, balance, skin protection, or autonomic function"],
    causes: ["Trauma such as a fall, collision, or sports injury", "Non-traumatic causes such as disease or compression", "Medical assessment is essential to understand the injury and associated risks"],
    diagnosis: ["The medical team diagnoses and classifies the injury using examination and imaging", "Rehabilitation clinicians assess mobility, transfers, wheelchair or walking skills, upper-limb function, skin safety, and daily tasks", "The plan is coordinated across the medical and rehabilitation team"],
    treatment: ["Transfer, bed mobility, wheelchair, walking, or assistive-device training", "Strength, balance, endurance, and functional task practice", "Self-care, home access, skin-protection, and caregiver education", "Equipment and environmental recommendations in coordination with the care team"],
    benefits: ["Safer transfers and mobility", "Greater independence in daily routines", "Better confidence with equipment, pacing, and home participation"],
    recoveryTimeline: "Progress depends on injury level and completeness, medical complications, rehabilitation access, health, equipment, and personal goals. Long-term rehabilitation and periodic reassessment may be appropriate.",
    relatedServices: ["Neurological Rehabilitation", "Occupational Therapy & Daily-Activity Retraining"],
    faqs: [{ question: "Can spinal cord injury rehabilitation continue after inpatient care?", answer: "Yes, many people continue with outpatient or home-based goals, but the appropriate plan depends on medical status, equipment, precautions, and the discharge team’s recommendations." }],
  },
  {
    slug: "traumatic-brain-injury",
    name: "Traumatic Brain Injury",
    title: "Traumatic Brain Injury Rehabilitation Support",
    metaDescription: "Explore physical and occupational therapy support after traumatic brain injury, including balance, mobility, fatigue, and daily tasks.",
    intro: "Traumatic brain injury can affect movement, balance, thinking, fatigue, vision, and daily participation. Rehabilitation is coordinated around safety and the person’s changing needs.",
    symptoms: ["Balance, coordination, walking, or movement changes", "Fatigue, reduced attention, slowed processing, or difficulty organizing tasks", "Headache, dizziness, vision changes, or difficulty returning to work and routine"],
    causes: ["Falls, vehicle collisions, sports injuries, workplace incidents, or other impacts", "The effects depend on the location and severity of the injury", "New or worsening neurological symptoms require medical assessment"],
    diagnosis: ["The medical team evaluates the injury, symptoms, and need for imaging or observation", "Therapists assess mobility, balance, endurance, daily tasks, cognition-related participation, and environmental safety", "Care may include coordination with medical, speech-language, psychology, or vocational professionals"],
    treatment: ["Graded mobility, balance, coordination, and endurance training", "Task organization, pacing, environmental modification, and daily-activity strategies", "Education for the person and caregivers", "A gradual return-to-school, work, exercise, or community participation plan when appropriate"],
    benefits: ["Safer movement and daily routines", "Better pacing and confidence with activity", "Practical strategies for participation while symptoms are monitored"],
    recoveryTimeline: "Recovery varies with injury severity, symptoms, sleep, mood, medical factors, and the demands of daily life. Progress is usually monitored in stages, with medical review for new or worsening symptoms.",
    relatedServices: ["Neurological Rehabilitation", "Occupational Therapy & Daily-Activity Retraining"],
    faqs: [{ question: "Can I exercise after a traumatic brain injury?", answer: "Activity should be guided by your medical and rehabilitation team. A gradual plan may be appropriate, but worsening headache, dizziness, confusion, vomiting, or neurological symptoms need medical review." }],
  },
  {
    slug: "parkinsons-disease",
    name: "Parkinson's Disease",
    title: "Parkinson's Disease Rehabilitation Support",
    metaDescription: "Learn how physical and occupational therapy may support movement, balance, walking, daily activities, and confidence with Parkinson's disease.",
    intro: "Rehabilitation for Parkinson’s disease focuses on meaningful movement and daily participation while adapting to symptoms, medication timing, and progression.",
    symptoms: ["Slowness, stiffness, tremor, or changes in movement amplitude", "Balance, walking, turning, or freezing concerns", "Difficulty with transfers, fine-motor tasks, posture, or everyday routines"],
    causes: ["Parkinson’s disease is a neurological condition with complex causes", "Symptoms and progression vary between people", "Diagnosis and medication management belong to a qualified medical provider"],
    diagnosis: ["A neurologist or qualified provider diagnoses Parkinson’s disease from history and examination", "Therapists assess movement, balance, walking, transfers, daily tasks, and safety", "The plan may consider medication cycles, fatigue, cognition, and home support"],
    treatment: ["Large-amplitude, cueing, balance, gait, and turning practice when appropriate", "Strength, flexibility, endurance, and fall-risk strategies", "Occupational therapy for routines, hand function, and home adaptations", "Caregiver education and a sustainable home program"],
    benefits: ["Improved confidence with walking and daily movement", "Practical strategies for transfers, turning, and home safety", "Support for maintaining participation as needs change"],
    recoveryTimeline: "Parkinson’s disease is generally managed over time rather than cured by a short rehabilitation course. Goals and strategies should be reviewed as symptoms, medication, and participation needs change.",
    relatedServices: ["Neurological Rehabilitation", "Occupational Therapy & Daily-Activity Retraining"],
    faqs: [{ question: "Should therapy be scheduled around medication timing?", answer: "Medication timing can affect movement for some people. Share your routine with the clinic so the clinician can discuss a practical schedule with you." }],
  },
  {
    slug: "progressive-supranuclear-palsy",
    name: "Progressive Supranuclear Palsy",
    title: "Progressive Supranuclear Palsy Rehabilitation Support",
    metaDescription: "Explore rehabilitation considerations for progressive supranuclear palsy, including fall prevention, transfers, mobility, and daily activities.",
    intro: "Progressive supranuclear palsy can affect balance, eye movement, posture, speech, swallowing, and daily function. Rehabilitation is coordinated with the neurological team and caregivers.",
    symptoms: ["Early balance or walking difficulties and increased fall risk", "Stiffness, postural changes, or trouble with transfers", "Changes in eye movement, speech, swallowing, attention, or daily tasks"],
    causes: ["Progressive supranuclear palsy is a progressive neurological condition", "The cause is not usually known and is different from ordinary balance problems", "A neurologist should evaluate suspected or changing neurological symptoms"],
    diagnosis: ["A neurologist diagnoses PSP using history, neurological examination, and the pattern of symptoms", "Therapists assess safety, transfers, walking, balance, posture, daily activities, and caregiver needs", "Coordination with speech-language, medical, and community services may be important"],
    treatment: ["Fall-risk reduction, transfer, walking, and positioning strategies", "Strength, mobility, and safe activity practice within tolerance", "Occupational therapy for home setup, daily tasks, and equipment needs", "Caregiver education and coordination with the medical team"],
    benefits: ["Safer movement and daily routines", "Better caregiver confidence and planning", "Practical strategies that support participation and comfort as needs evolve"],
    recoveryTimeline: "PSP is progressive, so rehabilitation goals focus on safety, function, participation, and quality of life rather than a fixed recovery endpoint. Plans should be reviewed regularly.",
    relatedServices: ["Neurological Rehabilitation", "Occupational Therapy & Daily-Activity Retraining"],
    faqs: [{ question: "What is the priority in PSP rehabilitation?", answer: "Safety, fall prevention, transfers, daily participation, and caregiver support are common priorities. The treatment team should tailor goals to the person’s symptoms and medical plan." }],
  },
  {
    slug: "multiple-sclerosis",
    name: "Multiple Sclerosis",
    title: "Multiple Sclerosis Rehabilitation Support",
    metaDescription: "Learn how rehabilitation may support mobility, fatigue management, balance, strength, and daily activities for people with multiple sclerosis.",
    intro: "Multiple sclerosis affects people differently and rehabilitation is adjusted for symptoms, fatigue, heat sensitivity, relapses, medication, and personal participation goals.",
    symptoms: ["Changes in strength, balance, walking, coordination, or sensation", "Fatigue that affects work, self-care, or exercise", "Spasticity, vision changes, cognitive concerns, or difficulty with daily tasks"],
    causes: ["Multiple sclerosis is an immune-mediated neurological condition affecting the central nervous system", "The pattern and severity of symptoms vary widely", "Diagnosis and disease-modifying treatment are managed by a qualified medical provider"],
    diagnosis: ["A neurologist uses history, examination, and investigations to diagnose MS", "Therapists evaluate mobility, balance, strength, fatigue, endurance, and daily participation", "The plan is adjusted around relapses, heat sensitivity, medication, and energy levels"],
    treatment: ["Energy conservation, pacing, and fatigue-management education", "Individualized strength, mobility, balance, and endurance work", "Walking, transfer, equipment, and home-safety strategies", "Occupational therapy for routines, work, self-care, and environmental modifications"],
    benefits: ["More manageable daily routines", "Improved confidence with movement and energy planning", "A flexible plan that adapts to changing symptoms and priorities"],
    recoveryTimeline: "MS symptoms can fluctuate and may progress differently between people. Rehabilitation goals are reviewed regularly and may change during or after a relapse.",
    relatedServices: ["Neurological Rehabilitation", "Occupational Therapy & Daily-Activity Retraining"],
    faqs: [{ question: "How should fatigue affect therapy planning?", answer: "Fatigue is a central part of planning for many people with MS. Tell the clinician when symptoms are most limiting so activity, rest, temperature, and scheduling can be considered." }],
  },
  {
    slug: "guillain-barre-syndrome",
    name: "Guillain-Barré Syndrome",
    title: "Guillain-Barré Syndrome Rehabilitation Support",
    metaDescription: "Explore rehabilitation considerations after Guillain-Barré syndrome, including strength, fatigue, mobility, transfers, and daily function.",
    intro: "Recovery after Guillain-Barré syndrome can involve weakness, fatigue, altered sensation, and changes in mobility. Rehabilitation must be paced carefully and coordinated with medical care.",
    symptoms: ["Weakness that may affect the legs, arms, or breathing muscles", "Difficulty walking, transferring, or using the hands", "Fatigue, altered sensation, pain, or reduced endurance during recovery"],
    causes: ["Guillain-Barré syndrome is an acute immune-mediated nerve disorder", "It can follow an infection or other trigger, but the cause is not always clear", "New or worsening weakness, breathing difficulty, or swallowing problems require emergency medical care"],
    diagnosis: ["The medical team diagnoses GBS through neurological examination and appropriate investigations", "Therapists assess strength, sensation, fatigue, mobility, transfers, breathing-related tolerance, and daily tasks", "The plan follows medical precautions and avoids overwork or unsafe fatigue"],
    treatment: ["Carefully graded mobility, strengthening, and endurance activities", "Transfer, walking, wheelchair, and self-care training", "Energy-conservation, pacing, positioning, and caregiver education", "Ongoing communication with the medical team when symptoms change"],
    benefits: ["Safer mobility and transfers", "Better pacing and confidence during recovery", "Support for returning to meaningful daily tasks without overloading recovery"],
    recoveryTimeline: "Recovery is variable and may continue for months or longer. Strength, fatigue, sensation, medical complications, and activity tolerance should guide progression rather than a fixed schedule.",
    relatedServices: ["Neurological Rehabilitation", "Occupational Therapy & Daily-Activity Retraining"],
    faqs: [{ question: "Why does pacing matter after GBS?", answer: "Nerves and muscles may fatigue easily during recovery. A clinician can help balance activity and rest and adjust the plan when fatigue, weakness, pain, or other symptoms increase." }],
  },
  {
    slug: "amyotrophic-lateral-sclerosis",
    name: "Amyotrophic Lateral Sclerosis",
    title: "ALS Rehabilitation and Participation Support",
    metaDescription: "Learn how rehabilitation may support safety, energy conservation, equipment, mobility, and daily participation for people living with ALS.",
    intro: "ALS rehabilitation focuses on safety, comfort, energy conservation, communication with the care team, and participation in meaningful activities as needs change.",
    symptoms: ["Progressive weakness affecting movement or daily tasks", "Changes in walking, transfers, hand use, speech, swallowing, or breathing", "Fatigue, cramps, stiffness, or difficulty maintaining activity"],
    causes: ["ALS is a progressive neurological disease affecting motor neurons", "The cause can vary and may be unclear", "Diagnosis and medical management require a qualified neurological team"],
    diagnosis: ["A neurologist establishes the diagnosis using history, examination, and investigations", "Therapists assess function, fatigue, mobility, transfers, equipment, and participation goals", "Care is coordinated with respiratory, speech-language, nutrition, medical, and caregiver support when needed"],
    treatment: ["Energy conservation, pacing, positioning, and safe movement strategies", "Equipment, transfer, mobility, and home-access recommendations", "Gentle activity and range-of-motion work when appropriate", "Occupational therapy for daily tasks, adaptive tools, and caregiver education"],
    benefits: ["Safer participation and reduced task burden", "Better planning for equipment and changing needs", "Support for comfort, independence, and meaningful routines"],
    recoveryTimeline: "ALS is progressive, so rehabilitation goals emphasize safety, quality of life, participation, and adaptation rather than recovery to a fixed endpoint. Plans should be reviewed as needs change.",
    relatedServices: ["Neurological Rehabilitation", "Occupational Therapy & Daily-Activity Retraining"],
    faqs: [{ question: "What is the role of therapy in ALS?", answer: "Therapy can help with safety, energy conservation, mobility, equipment, positioning, daily activities, and caregiver planning. It should be coordinated with the person’s neurological and respiratory care team." }],
  },
  {
    slug: "cerebral-palsy",
    name: "Cerebral Palsy",
    title: "Cerebral Palsy Rehabilitation Support",
    metaDescription: "Explore pediatric and lifelong rehabilitation support for cerebral palsy, including movement, participation, equipment, and daily activities.",
    intro: "Cerebral palsy affects movement and posture in different ways. Therapy goals should be meaningful, family-centered, and appropriate for the person’s age, development, and participation.",
    symptoms: ["Differences in muscle tone, movement control, balance, or coordination", "Challenges with walking, hand use, communication, play, school, or self-care", "Fatigue, pain, contracture risk, or equipment needs may develop over time"],
    causes: ["Cerebral palsy results from a developing brain difference or injury affecting movement", "The timing and contributing factors vary", "A medical team should assess changing function, pain, seizures, feeding, or other concerns"],
    diagnosis: ["Medical and developmental teams evaluate movement, development, tone, and function", "Therapists assess play, mobility, balance, hand use, daily activities, and environmental participation", "Goals are set with the child, family, school, and care team when appropriate"],
    treatment: ["Play-based strength, balance, mobility, and motor-learning activities", "Gait, transfers, positioning, and equipment support", "Occupational therapy for hand skills, self-care, school, and sensory-motor tasks", "Caregiver coaching and home or school strategies"],
    benefits: ["Greater participation in play, school, self-care, and family routines", "Improved confidence and practical mobility skills", "A plan that adapts as the child grows and priorities change"],
    recoveryTimeline: "Cerebral palsy is a lifelong condition, but skills, participation, and support needs can change. Progress is individualized and should be measured against meaningful functional goals.",
    relatedServices: ["Pediatric Physical & Occupational Therapy", "Occupational Therapy & Daily-Activity Retraining"],
    faqs: [{ question: "How are therapy goals chosen for a child with cerebral palsy?", answer: "Goals are built around the child’s daily participation, family priorities, development, environment, safety, and medical recommendations rather than a single exercise or milestone." }],
  },
  {
    slug: "global-developmental-delay",
    name: "Global Developmental Delay",
    title: "Global Developmental Delay Rehabilitation Support",
    metaDescription: "Learn how pediatric physical and occupational therapy may support movement, play, communication participation, and daily skills with developmental delay.",
    intro: "Children with global developmental delay may benefit from early, family-centered support that connects movement and daily skills to play, communication, learning, and participation.",
    symptoms: ["Delays across more than one developmental area", "Difficulty with gross motor, fine motor, play, self-care, communication, or social participation", "Differences in balance, coordination, strength, sensory processing, or task engagement"],
    causes: ["Developmental delay can have many possible causes, including genetic, neurological, medical, or environmental factors", "Sometimes the cause is not immediately known", "A pediatrician or developmental specialist should guide medical evaluation"],
    diagnosis: ["A qualified pediatric or developmental team evaluates milestones, health, hearing, vision, and participation", "Therapists observe play, movement, hand skills, communication participation, and daily routines", "Assessment may be coordinated with speech-language, educational, medical, and family supports"],
    treatment: ["Play-based movement, balance, coordination, and strength activities", "Fine-motor, self-care, sensory-motor, and task-participation practice", "Caregiver coaching for everyday routines and home opportunities", "Communication with school and other providers when appropriate"],
    benefits: ["More opportunities for active participation and learning", "Improved confidence in play and daily routines", "Practical strategies that help caregivers support development at home"],
    recoveryTimeline: "Developmental progress is individual and can change with health, opportunity, support, and the child’s needs. Goals should be reviewed regularly with the family and developmental team.",
    relatedServices: ["Pediatric Physical & Occupational Therapy", "Occupational Therapy & Daily-Activity Retraining"],
    faqs: [{ question: "When should a parent ask about developmental support?", answer: "If you are concerned about a child’s development, discuss it with the child’s pediatrician or developmental provider. Early evaluation can help identify appropriate supports without waiting for a problem to resolve on its own." }],
  },
];

export const conditionBySlug = new Map(conditionPages.map((condition) => [condition.slug, condition]));
